const STORAGE='brujula_v02_sessions';
const SCHEMA=2;
const RETENTION_DAYS=180;
const BOOK_URLS={focus:'https://www.amazon.com/dp/B0H4FSQ7CZ',axo:'https://www.amazon.com/dp/B0GPLZZKRK'};
const STATE={focus:newRouteState(),axo:newRouteState()};
function newRouteState(){return{scores:[],candidates:[],close:[],chosen:null,context:'',touched:new Set(),analysisValid:false,saved:false,ideal:false}}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function safeStatusLabel(s){const map={pendiente:'pendiente',hecha:'hecha',parcial:'parcial',no_hecha:'no realizada',replantear:'a replantear'};return map[s]||'estado desconocido'}
function nowIso(){return new Date().toISOString()}
function isValidSession(x){return x&&typeof x==='object'&&typeof x.date==='string'&&['focus','axo'].includes(x.key)&&typeof x.framework==='string'&&typeof x.area==='string'&&typeof x.action==='string'&&['pendiente','hecha','parcial','no_hecha','replantear'].includes(x.status)}
function normalizeSession(x){return{id:Number.isFinite(+x.id)?+x.id:Date.now(),schemaVersion:SCHEMA,date:x.date,key:x.key,framework:x.framework,area:x.area,action:x.action,status:x.status,followDate:typeof x.followDate==='string'?x.followDate:undefined,context:x.schemaVersion===SCHEMA&&typeof x.context==='string'?x.context.slice(0,280):undefined}}
function getSessions(){
  try{
    const raw=localStorage.getItem(STORAGE);if(!raw)return[];
    const parsed=JSON.parse(raw);if(!Array.isArray(parsed))return[];
    const cutoff=Date.now()-RETENTION_DAYS*86400000;
    const cleaned=parsed.filter(isValidSession).map(normalizeSession).filter(x=>{const t=Date.parse(x.date);return Number.isFinite(t)&&t>=cutoff}).slice(-20);
    const normalized=JSON.stringify(cleaned);if(normalized!==JSON.stringify(parsed))try{localStorage.setItem(STORAGE,normalized)}catch(_e){}
    return cleaned;
  }catch(_e){return[]}
}
function putSessions(x){
  try{localStorage.setItem(STORAGE,JSON.stringify(x.filter(isValidSession).map(normalizeSession).slice(-20)));setStorageNotice('');return true}
  catch(_e){setStorageNotice('No fue posible guardar tu recorrido en este navegador. La reflexión actual sigue disponible, pero no podremos retomarla después.','error');return false}
}
function setStorageNotice(msg,kind=''){const el=document.getElementById('storageNotice');if(!el)return;el.className='note '+kind;el.textContent=msg}
function fmtDate(iso){try{return new Date(iso).toLocaleDateString('es-MX',{day:'2-digit',month:'short',year:'numeric'})}catch(_e){return''}}
function requiredCount(key){return ROUTES[key].dimensions.reduce((n,d)=>n+d.questions.length,0)}
function markTouched(key,di,qi){STATE[key].touched.add(`${di}:${qi}`)}
function allAnswered(key){return STATE[key].touched.size===requiredCount(key)}
function invalidateAnalysis(key,message='Tus respuestas cambiaron. Vuelve a generar la reflexión para mantener el resultado consistente.'){
  if(!STATE[key].analysisValid)return;
  STATE[key].analysisValid=false;STATE[key].saved=false;STATE[key].ideal=false;
  const e=document.getElementById(key+'Res');e.className='res stale';e.innerHTML=`<div><b>Reflexión pendiente de actualizar</b><p>${esc(message)}</p></div>`;
}
function renderForm(key){
  const r=ROUTES[key],el=document.getElementById(key+'Form');let h='<h3>Check-in breve</h3><p class="lead">Responde cada pregunta pensando en cómo te sientes hoy o en los últimos días. No hay respuestas correctas.</p>';
  r.dimensions.forEach((d,di)=>{
    h+=`<fieldset class="dim"><legend><div class="dimhead"><b>${esc(d.code)} · ${esc(d.name)}</b><span class="avg" id="${key}avg${di}">—</span></div></legend>`;
    d.questions.forEach((q,qi)=>{const id=`${key}_${di}_${qi}`,qid=id+'label';h+=`<div class="q"><div class="qt"><label id="${qid}" for="${id}" style="margin:0;font-size:13px;font-weight:400">${esc(q)}</label><span class="sc unanswered" id="${id}s">Sin responder</span></div><input id="${id}" type="range" min="1" max="5" value="3" aria-labelledby="${qid}" aria-valuemin="1" aria-valuemax="5" aria-valuenow="3" oninput="syncScore('${key}',${di},${qi})"><div class="scale" aria-hidden="true"><span>${esc(r.scale[0])}</span><span>${esc(r.scale[1])}</span></div></div>`});h+='</fieldset>';
  });
  h+=`<div class="context"><label for="${key}Context">Si quieres, añade una frase de contexto</label><textarea id="${key}Context" maxlength="280" placeholder="Ej. Estoy tomando una decisión laboral y me cuesta distinguir entre lo que quiero y lo que esperan de mí." oninput="contextChanged('${key}')"></textarea><p class="lead" style="margin-top:7px">En esta versión el contexto no es interpretado por IA. Se usa como ancla visible para tu reflexión. Sólo se guardará localmente si eliges expresamente conservarlo junto con tu microacción.</p></div><div class="row"><button type="button" class="btn" id="${key}Analyze" onclick="analyze('${key}')">${esc(r.button)}</button><button type="button" class="ghost" onclick="example('${key}')">Probar ejemplo</button></div><div id="${key}FormMsg" class="note" aria-live="polite"></div>`;
  el.innerHTML=h;
}
function syncScore(key,di,qi){
  markTouched(key,di,qi);const id=`${key}_${di}_${qi}`,input=document.getElementById(id),v=+input.value;input.setAttribute('aria-valuenow',String(v));const s=document.getElementById(id+'s');s.textContent=v+'/5';s.classList.remove('unanswered');
  const qs=ROUTES[key].dimensions[di].questions;const vals=[];let all=true;qs.forEach((_,j)=>{if(!STATE[key].touched.has(`${di}:${j}`))all=false;vals.push(+document.getElementById(`${key}_${di}_${j}`).value)});document.getElementById(key+'avg'+di).textContent=all?(vals.reduce((a,b)=>a+b,0)/vals.length).toFixed(1)+'/5':'—';invalidateAnalysis(key)
}
function contextChanged(key){invalidateAnalysis(key,'Cambiaste el contexto. Vuelve a generar la reflexión para que el resultado y lo que guardes correspondan a la misma sesión.')}
function openRoute(key){document.getElementById('home').style.display='none';document.querySelectorAll('.app').forEach(x=>x.classList.remove('on'));document.getElementById(key).classList.add('on');document.getElementById(key).scrollIntoView({behavior:'smooth'});document.getElementById(key+'Title').focus?.()}
function goHome(){document.querySelectorAll('.app').forEach(x=>x.classList.remove('on'));document.getElementById('home').style.display='block';renderFollow();document.getElementById('home').scrollIntoView({behavior:'smooth'})}
function scoresFor(key){return ROUTES[key].dimensions.map((d,di)=>{const v=d.questions.map((_,qi)=>+document.getElementById(`${key}_${di}_${qi}`).value);return v.reduce((a,b)=>a+b,0)/v.length})}
function analyze(key){
  const msg=document.getElementById(key+'FormMsg');msg.textContent='';
  if(!allAnswered(key)){const left=requiredCount(key)-STATE[key].touched.size;msg.textContent=`Faltan ${left} ${left===1?'respuesta':'respuestas'} antes de generar tu reflexión.`;return}
  const scores=scoresFor(key);
  STATE[key].scores=scores;STATE[key].context=document.getElementById(key+'Context').value.trim();STATE[key].analysisValid=true;STATE[key].saved=false;
  if(scores.every(v=>Math.abs(v-5)<0.01)){
    STATE[key].ideal=true;STATE[key].candidates=[];STATE[key].close=[];STATE[key].chosen=null;renderIdeal(key);return;
  }
  STATE[key].ideal=false;
  const min=Math.min(...scores),candidates=scores.map((v,i)=>({v,i})).filter(x=>Math.abs(x.v-min)<0.01).map(x=>x.i),close=scores.map((v,i)=>({v,i})).filter(x=>x.v>min&&x.v<=min+.5).sort((a,b)=>a.v-b.v).map(x=>x.i);
  STATE[key].candidates=candidates;STATE[key].close=close;STATE[key].chosen=candidates.length===1?candidates[0]:null;
  if(candidates.length>1)renderChoice(key);else renderResult(key,candidates[0])
}
function renderChoice(key){const s=STATE[key],r=ROUTES[key],e=document.getElementById(key+'Res');e.className='res';const buttons=s.candidates.map(i=>`<button type="button" class="choicebtn" onclick="chooseArea('${key}',${i})">${esc(r.dimensions[i].code)} · ${esc(r.dimensions[i].name)}</button>`).join('');e.innerHTML=`<span class="rbadge ${r.badge}">${esc(r.resultLabel)}</span><h2>Hoy aparecen varias áreas al mismo nivel</h2><p>No hay un único mínimo en tus respuestas. En lugar de elegir arbitrariamente por ti, Brújula te propone escoger cuál quieres explorar primero.</p><div class="choose"><b>Elige un punto de entrada</b><div class="choicegrid">${buttons}</div></div><div class="note">Un empate no significa que “todo esté mal”. Sólo indica que tus respuestas no diferencian con claridad una sola dimensión en este momento.</div>`;e.focus()}
function chooseArea(key,i){if(!STATE[key].analysisValid||STATE[key].ideal)return;STATE[key].chosen=i;STATE[key].close=STATE[key].candidates.filter(x=>x!==i).concat(STATE[key].close).slice(0,3);renderResult(key,i)}
function renderResult(key,i){
  if(!STATE[key].analysisValid||STATE[key].ideal)return;const s=STATE[key],r=ROUTES[key],d=r.dimensions[i],e=document.getElementById(key+'Res');e.className='res';const context=s.context?`<div class="contextbox"><b>Tu contexto</b><p>“${esc(s.context)}”</p><p>Úsalo como ancla: relee esta frase a la luz de la dimensión que estás explorando.</p></div>`:'';const near=s.close.length?`<div class="near"><b>Áreas cercanas</b><p>${s.close.map(x=>esc(r.dimensions[x].code)+' · '+esc(r.dimensions[x].name)).join(' · ')}</p><p>No es necesario trabajarlas todas hoy; simplemente quedan visibles como posibles conexiones.</p></div>`:'';const title1=key==='focus'?'Reconoce':'Observa',title2=key==='focus'?'Resignifica':'Pregunta detonadora';const acts=d.actions.map(a=>`<label class="actionopt"><input type="radio" name="${key}Action" value="${esc(a)}"><span>${esc(a)}</span></label>`).join('');
  e.innerHTML=`<span class="rbadge ${r.badge}">${esc(r.resultLabel)}</span><h2>${esc(d.code)} · ${esc(d.name)}</h2>${context}<h4>${title1}</h4><p>${esc(d.observe)}</p><h4>${title2}</h4><p>${esc(d.reframe)}</p>${near}<div class="act"><h4 style="margin-top:0">Elige una microacción</h4><p>No tienes que hacer las tres. El valor está en elegir una acción suficientemente pequeña para intentar de verdad.</p><div class="actionlist">${acts}</div><div class="customaction"><label for="${key}Custom">O escribe tu propia microacción</label><input type="text" id="${key}Custom" maxlength="180" placeholder="Mi acción concreta será..."></div><label class="savecontext"><input type="checkbox" id="${key}SaveContext"><span>Guardar también mi frase de contexto en este dispositivo. Déjalo sin marcar si prefieres conservar sólo la microacción.</span></label><div class="note">Si una microacción involucra a otra persona o una situación sensible, hazla sólo si es segura y apropiada para tu contexto. No necesitas realizar ninguna acción que pueda ponerte en riesgo.</div><div class="row"><button type="button" class="btn" id="${key}SaveBtn" onclick="saveAction('${key}',${i})">Guardar mi acción</button></div><div id="${key}SaveMsg" class="note" aria-live="polite"></div></div><h4>Pista de Brújula entre marcos</h4><p>${esc(d.connection)}</p><div class="note">Esta conexión es una interpretación de diseño de Brújula PotencIA; no forma parte de la estructura original de los libros.</div><div class="book"><b>Para profundizar</b><p>Esta experiencia es una puerta de entrada. El desarrollo completo del tema corresponde a <b>${esc(d.deepen)}</b> de <em>${r.framework==='F.O.C.U.S.'?'F.O.C.U.S.':'La Sabiduría del Ajolote'}</em>, de la Dra. Claudia Jones.</p><a class="link" href="${BOOK_URLS[key]}" target="_blank" rel="noopener noreferrer">Adquirir el libro →</a></div><div class="note">Herramienta educativa y reflexiva. No constituye diagnóstico, terapia ni recomendación clínica.</div>`;e.focus()
}
function renderIdeal(key){
  if(!STATE[key].analysisValid||!STATE[key].ideal)return;const s=STATE[key],r=ROUTES[key],d=r.ideal,e=document.getElementById(key+'Res');e.className='res';const context=s.context?`<div class="contextbox"><b>Tu contexto</b><p>“${esc(s.context)}”</p><p>Úsalo como ancla para reconocer qué está funcionando y qué quieres sostener.</p></div>`:'';const title1=key==='focus'?'Reconoce':'Observa',title2=key==='focus'?'Resignifica':'Integra';const acts=d.actions.map(a=>`<label class="actionopt"><input type="radio" name="${key}IdealAction" value="${esc(a)}"><span>${esc(a)}</span></label>`).join('');
  e.innerHTML=`<span class="rbadge ${r.badge}">${esc(d.label||r.resultLabel)}</span><h2>${esc(d.title)}</h2>${context}<h4>${title1}</h4><p>${esc(d.observe)}</p><h4>${title2}</h4><p>${esc(d.reframe)}</p><div class="act"><h4 style="margin-top:0">Elige una microacción de mantenimiento</h4><p>No necesitas inventar un problema. Si hoy todo se siente sólido, puedes usar Brújula para reconocer y cuidar las condiciones que están funcionando.</p><div class="actionlist">${acts}</div><div class="customaction"><label for="${key}IdealCustom">O escribe tu propia microacción</label><input type="text" id="${key}IdealCustom" maxlength="180" placeholder="Mi acción para sostener este equilibrio será..."></div><label class="savecontext"><input type="checkbox" id="${key}IdealSaveContext"><span>Guardar también mi frase de contexto en este dispositivo. Déjalo sin marcar si prefieres conservar sólo la microacción.</span></label><div class="row"><button type="button" class="btn" id="${key}IdealSaveBtn" onclick="saveIdealAction('${key}')">Guardar mi acción</button></div><div id="${key}IdealSaveMsg" class="note" aria-live="polite"></div></div><div class="book"><b>Para profundizar</b><p>Si quieres comprender cómo sostener este equilibrio, puedes profundizar en <b>${esc(d.deepen)}</b> de <em>${r.framework==='F.O.C.U.S.'?'F.O.C.U.S.':'La Sabiduría del Ajolote'}</em>, de la Dra. Claudia Jones.</p><a class="link" href="${BOOK_URLS[key]}" target="_blank" rel="noopener noreferrer">Adquirir el libro →</a></div><div class="note">Un 5/5 en todas las respuestas describe tu autoobservación de hoy; no certifica perfección, salud mental, ausencia de riesgo ni una condición permanente.</div>`;e.focus()
}
function saveAction(key,i){
  const msg=document.getElementById(key+'SaveMsg');if(!STATE[key].analysisValid||STATE[key].ideal){msg.textContent='Vuelve a generar la reflexión antes de guardar una acción.';return}if(STATE[key].saved){msg.textContent='Esta acción ya fue guardada.';return}
  const pending=latestPending();if(pending){msg.textContent='Ya tienes una microacción pendiente. Indica primero cómo te fue con ella antes de guardar una nueva.';document.getElementById('followCard').scrollIntoView({behavior:'smooth'});return}
  const custom=document.getElementById(key+'Custom').value.trim(),picked=document.querySelector(`input[name="${key}Action"]:checked`),action=custom||(picked?picked.value:'');if(!action){msg.textContent='Elige una microacción o escribe una propia antes de guardar.';return}
  const r=ROUTES[key],d=r.dimensions[i],saveContext=document.getElementById(key+'SaveContext').checked,sessions=getSessions(),item={id:Date.now(),schemaVersion:SCHEMA,date:nowIso(),key,framework:r.framework,area:d.code+' · '+d.name,action,status:'pendiente'};if(saveContext&&STATE[key].context)item.context=STATE[key].context;
  sessions.push(item);if(!putSessions(sessions)){msg.textContent='No fue posible guardar la acción en este navegador.';return}STATE[key].saved=true;const btn=document.getElementById(key+'SaveBtn');btn.disabled=true;msg.className='note ok';msg.textContent='Acción guardada ✓ La próxima vez Brújula podrá preguntarte cómo te fue.';renderHistory();renderFollow()
}
function saveIdealAction(key){
  const msg=document.getElementById(key+'IdealSaveMsg');if(!STATE[key].analysisValid||!STATE[key].ideal){msg.textContent='Vuelve a generar la reflexión antes de guardar una acción.';return}if(STATE[key].saved){msg.textContent='Esta acción ya fue guardada.';return}
  const pending=latestPending();if(pending){msg.textContent='Ya tienes una microacción pendiente. Indica primero cómo te fue con ella antes de guardar una nueva.';document.getElementById('followCard').scrollIntoView({behavior:'smooth'});return}
  const custom=document.getElementById(key+'IdealCustom').value.trim(),picked=document.querySelector(`input[name="${key}IdealAction"]:checked`),action=custom||(picked?picked.value:'');if(!action){msg.textContent='Elige una microacción o escribe una propia antes de guardar.';return}
  const r=ROUTES[key],d=r.ideal,saveContext=document.getElementById(key+'IdealSaveContext').checked,sessions=getSessions(),item={id:Date.now(),schemaVersion:SCHEMA,date:nowIso(),key,framework:r.framework,area:d.area,action,status:'pendiente'};if(saveContext&&STATE[key].context)item.context=STATE[key].context;
  sessions.push(item);if(!putSessions(sessions)){msg.textContent='No fue posible guardar la acción en este navegador.';return}STATE[key].saved=true;const btn=document.getElementById(key+'IdealSaveBtn');btn.disabled=true;msg.className='note ok';msg.textContent='Acción guardada ✓ La próxima vez Brújula podrá preguntarte cómo te fue.';renderHistory();renderFollow()
}
function latestPending(){const s=getSessions();for(let i=s.length-1;i>=0;i--)if(s[i].status==='pendiente')return{i,session:s[i]};return null}
function renderFollow(){const x=latestPending(),el=document.getElementById('followCard');if(!x){el.classList.remove('on');el.innerHTML='';return}const s=x.session;el.classList.add('on');el.innerHTML=`<div class="follow-top"><div><div class="k">Seguimiento</div><h3>La última vez elegiste una microacción</h3><p><b style="color:white">${esc(s.area)}</b> · ${esc(fmtDate(s.date))}<br>${esc(s.action)}</p></div><span class="stage">${esc(s.framework)}</span></div><div class="statusrow"><button type="button" class="statusbtn" onclick="setStatus(${x.i},'hecha')">La hice</button><button type="button" class="statusbtn" onclick="setStatus(${x.i},'parcial')">Parcialmente</button><button type="button" class="statusbtn" onclick="setStatus(${x.i},'no_hecha')">No la hice</button><button type="button" class="statusbtn" onclick="setStatus(${x.i},'replantear',true)">Quiero replantearla</button></div>`}
function setStatus(i,status,reopen=false){const s=getSessions();if(!s[i])return;s[i].status=status;s[i].followDate=nowIso();if(!putSessions(s))return;renderFollow();renderHistory();if(reopen){resetRoute(s[i].key);openRoute(s[i].key)}}
function renderHistory(){const s=getSessions(),el=document.getElementById('historyList');if(!s.length){el.textContent='Todavía no has guardado ninguna microacción.';return}el.innerHTML=s.slice().reverse().slice(0,6).map(x=>`<div class="histitem"><b>${esc(x.framework)} · ${esc(x.area)}</b><span class="hstatus">${esc(safeStatusLabel(x.status))}</span><br>${esc(fmtDate(x.date))} · ${esc(x.action)}${x.context?`<br><span style="color:#9aa2c8">Contexto guardado: ${esc(x.context)}</span>`:''}</div>`).join('')}
function clearHistory(){if(!confirm('¿Borrar todo el historial local de Brújula en este dispositivo?'))return;try{localStorage.removeItem(STORAGE);setStorageNotice('Historial local borrado.','ok')}catch(_e){setStorageNotice('No fue posible borrar el historial local en este navegador.','error')}renderHistory();renderFollow()}
function resetRoute(key){STATE[key]=newRouteState();renderForm(key);const e=document.getElementById(key+'Res');e.className='res empty';e.innerHTML=key==='focus'?'Tu reflexión aparecerá aquí.<br>La herramienta identifica áreas para explorar, no una calificación personal.':'Tu reflexión aparecerá aquí.<br>Propone un área de observación; no diagnostica.'}
function example(key){const vals=key==='focus'?[[4,4],[2,2],[4,3],[3,3],[4,4]]:[[4,4],[4,3],[3,3],[1,2],[3,3],[2,2],[4,4]];vals.forEach((pair,di)=>pair.forEach((v,qi)=>{const id=`${key}_${di}_${qi}`;document.getElementById(id).value=v;syncScore(key,di,qi)}));document.getElementById(key+'Context').value=key==='focus'?'Estoy considerando un cambio y me cuesta ver opciones sin sentir que debo resolver todo de inmediato.':'Siento que estoy aceptando demasiadas responsabilidades y me cuesta poner un límite claro.';STATE[key].analysisValid=false;analyze(key)}
renderForm('focus');renderForm('axo');renderFollow();renderHistory();